# Generated by Django 4.2.2 on 2023-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_DAlbas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="precioProducto",
            field=models.DecimalField(
                db_comment="precio unitario del producto",
                decimal_places=3,
                max_digits=10,
            ),
        ),
    ]
