# Generated by Django 4.2.2 on 2023-10-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_DAlbas", "0002_alter_productos_precioproducto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="precioProducto",
            field=models.IntegerField(db_comment="precio unitario del producto"),
        ),
    ]
